version: 0.2

env:
    variables:
        environment: 'dev'
        ECR_REPO: '/home-app'

phases:
    pre_build:
        commands:
            - ls .
            - pwd
            - chmod +x ./scripts/*.sh
    build:
        commands:
            - echo Build started on `date`
            - ./scripts/build-docker.sh
        finally:
            - echo build phase finished
    post_build:
        commands:
            - echo Build completed on `date`
